language: node_js
node_js:
  - "14.4.0"
cache:
  directories:
    - "node_modules"
script:
  - "npm test"
branches:
  only:
    - master
notifications:
  email:
    on_success: always
    on_failure: always
